# Setup
title:            JSWU
tagline:          "Stronger Together"
description:      "JS Workers United"
url:              https://jstartunited.com
baseurl:          ""
paginate:         5
shareimage:       

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Author
author:
  name: "JSWU"
  email: pbr@duck.com

# Social Media Profiles
socialmedia:
  - title: Discord
    link: https://discord.gg/V756y55ZNg
    user: 
    fa-icon: 'fab fa-discord'