# Setup
title:            JSWU
tagline:          "Stronger Together"
description:      ""
url:              https://jstartunited.com
baseurl:          ""
paginate:         5
shareimage:       

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Author
author:
  name: "JSWU"
  email: pbr@duck.com

# Social Media Profiles
socialmedia:
  - title: Twitter
    link: www.twitter.com
    user: 
    fa-icon: 'fab fa-twitter'